### ISSUE TITLE
GetOccurences does not work properly when used with TimeZones

### ISSUE THREAD

**Issue by jsgoupil** [rianjs/ical.net#671] opened 2024-12-16 03:02 UTC
When using `GetOccurences` on recurring elements with a time zone, the data is not returned properly.
My example here is I set a recurring event on the 2nd of December, from midnight to 8am PST, repeating on Mondays.

Without time zones it works just fine.
```
private static void CheckCalendar(ServiceProvider provider)
{
    var calendar = new Ical.Net.Calendar();
    var blockDate = new DateTime(2024, 12, 2, 8, 0, 0, DateTimeKind.Utc);
    calendar.Events.Add(new CalendarEvent
    {
        Summary = "Some work",
        DtStart = new CalDateTime(blockDate),
        DtEnd = new CalDateTime(blockDate.Add(new TimeSpan(8, 0, 0))),
        IsAllDay = false,
        RecurrenceRules = new List<RecurrencePattern>
        {
            new RecurrencePattern
            {
                Frequency = Ical.Net.FrequencyType.Weekly,
                Interval = 1,
                ByDay = new List<WeekDay>
                {
                    new WeekDay(DayOfWeek.Monday)
                }
            }
        }
    });

    var start = new DateTime(2024, 12, 9, 8, 5, 0, DateTimeKind.Utc);
    var end = new DateTime(2024, 12, 10, 7, 59, 59, DateTimeKind.Utc);
    var x = calendar.GetOccurrences(start, end);
    Console.WriteLine(x.Count); // Is 1
}
```

Notice that my `start` is 5 minutes after the "DtStart" event, but I still get 1 entry.

Now I do the same thing but I attach the time zone on the `CalDateTime`

```
private static void CheckCalendarZone(ServiceProvider provider)
{
    var zone = "America/Los_Angeles";
    var calendar = new Ical.Net.Calendar();
    var blockDate = new DateTime(2024, 12, 2, 8, 0, 0, DateTimeKind.Utc);
    calendar.Events.Add(new CalendarEvent
    {
        Summary = "Unavailable Before Work",
        DtStart = new CalDateTime(blockDate).ToTimeZone(zone),
        DtEnd = new CalDateTime(blockDate.Add(new TimeSpan(8, 0, 0))).ToTimeZone(zone),
        IsAllDay = false,
        RecurrenceRules = new List<RecurrencePattern>
        {
            new RecurrencePattern
            {
                Frequency = Ical.Net.FrequencyType.Weekly,
                Interval = 1,
                ByDay = new List<WeekDay>
                {
                    new WeekDay(DayOfWeek.Monday)
                }
            }
        }
    });

    var start = new DateTime(2024, 12, 9, 8, 5, 0, DateTimeKind.Utc);
    var end = new DateTime(2024, 12, 10, 7, 59, 59, DateTimeKind.Utc);
    var x = calendar.GetOccurrences(start, end);
    Console.WriteLine(x.Count); // Should be 1
}
```

This time, I get nothing in my occurrences.
The only way I can get something is if my `start` is BEFORE midnight, so if I replace `start` with `var start = new DateTime(2024, 12, 9, 8, 0, 0, DateTimeKind.Utc).AddMilliseconds(-1);`
it starts working.

**Comment by minichma** [comment] 2024-12-16 08:35
This seems to be a duplicate of #660 and #670.

**Comment by axunonb** [comment] 2024-12-16 19:05
For `DtStart`and `DtEnd` it looks like you're trying to convert a date/time without a timezone using `ToTimeZone(zone)`.
You should rather create `CalDateTime` instances with the desired timezone directly.
The code below will meet your expectation with version `ical.net 4.3.1`.
Can you confirm?

```c#
public static void Main()
{
    var zone = "America/Los_Angeles";
    var calendar = new Ical.Net.Calendar();
    var blockDate = new DateTime(2024, 12, 2, 8, 0, 0, DateTimeKind.Utc);
    calendar.Events.Add(new CalendarEvent
    {
        Summary = "Unavailable Before Work",
        DtStart = new CalDateTime(blockDate, zone), //.ToTimeZone(zone),
        DtEnd = new CalDateTime(blockDate.Add(new TimeSpan(8, 0, 0)), zone), //.ToTimeZone(zone),
        //IsAllDay = false,
        RecurrenceRules = new List<RecurrencePattern>
        {
            new RecurrencePattern
            {
                Frequency = Ical.Net.FrequencyType.Weekly,
                Interval = 1,
                ByDay = new List<WeekDay>
                {
                    new WeekDay(DayOfWeek.Monday)
                }
            }
        }
    });

    var sss = new CalendarSerializer(calendar).SerializeToString();
    var start = new DateTime(2024, 12, 9, 8, 5, 0, DateTimeKind.Utc);
    var end = new DateTime(2024, 12, 10, 8, 0, 0, DateTimeKind.Utc);
    var x = calendar.GetOccurrences(start, end);
    
    // Should have 1 occurrence for
    // Start: 2024-12-09T00:00:00 (America/Los_Angeles, UTC-08:00), End: 2024-12-09T08:00:00 (America/Los_Angeles, UTC-08:00)

    Console.WriteLine(x.Count);
}
```

**Comment by jsgoupil** [comment] 2024-12-16 19:43
Thanks @axunonb for the explanation.

The `blockDate` in the image here
![image](https://github.com/user-attachments/assets/9a072e89-fa77-4d7f-940b-c20f54f5d0c9)

Is midnight PST. And there is a time zone, it's UTC.
So if we look at the Watch list, the first one is "correct".
The second one is incorrect (aka not what I want).

Like mentioned in the documentation
> Specifying a `tzId` value will override `value`'s `DateTimeKind` property

So by tweaking the `blockDate` and setting it to Local, it works
![image](https://github.com/user-attachments/assets/be493f25-af06-49dd-894a-4c2092b8037a)

BUT this is going around an ICal bug. I have to convert my UTC time to local before I use it with `CalDateTime`, which is unfortunate, but at least this is a work around.

**Comment by axunonb** [comment] 2024-12-16 20:08
Usage of `DateTimeKind` and `CalDateTime` in general is a difficult subject in v4, and we're on the way getting over it in v5 (current main branch). It already contains numerous fixes for bugs of v4.
There won't be a v4 release to fix `DateTimeKind` handling.

**Comment by jsgoupil** [comment] 2024-12-16 20:13
Actually, going with `Local` doesn't play well on build machines being in different time zones. I'll have to find a work around.
I understand the pain. DateTime is always a mess in .NET and this is the reason I used NodaTime as well.

**Closed as completed** 2024-12-22 15:22 UTC
Labels: bug, duplicate
